name: Fetch Apple News and Send to Feishu

on:
  schedule:
    # 定时任务（这里设置为每天午夜 12 点执行）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发工作流
    inputs:
      run_on_demand:
        description: 'Run workflow on demand'
        required: false
        default: 'false'

jobs:
  fetch_and_send_news:
    runs-on: ubuntu-latest # 使用 Ubuntu 作为运行环境

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. 执行 Python 脚本来抓取苹果新闻并推送到飞书
      - name: Fetch Apple News and Send to Feishu
        run: |
          python fetch_apple_news.py
